server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name api-roborock.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app roborock-local-server;
        set $upstream_port 555;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
